# Fetch ubuntu 22.04 LTS docker image
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive 
#[DEPRECATED] Make a copy of ubuntu apt repository before modifying it. 
#RUN mv /etc/apt/sources.list /sources.list
#[DEPRECATED] Now change the default ubuntu apt repositry, which is VERY slow, to another mirror that is much faster. It assumes the host already has created a sources.list.
#COPY sources.list /etc/apt/sources.list

# Update apt, and install Java + curl + wget on your ubuntu image.
RUN apt-get update && \
    apt-get install -y \
    curl \
    vim \
    wget \
    expect \
    git \
    zip \
    unzip \
    openjdk-21-jdk \
    python3 \
    && apt-get clean

RUN curl -s "https://archive.apache.org/dist/hadoop/core/hadoop-3.3.6/hadoop-3.3.6.tar.gz" | tar -xz -C /usr/local/ \
    && ln -s /usr/local/hadoop-3.3.6 /usr/local/hadoop \
    && chmod a+rwx -R /usr/local/hadoop/

ENV HADOOP_PREFIX /usr/local/hadoop
ENV HADOOP_COMMON_HOME /usr/local/hadoop
ENV HADOOP_HDFS_HOME /usr/local/hadoop
ENV HADOOP_MAPRED_HOME /usr/local/hadoop
ENV HADOOP_YARN_HOME /usr/local/hadoop
ENV HADOOP_CONF_DIR /usr/local/hadoop/etc/hadoop
ENV YARN_CONF_DIR $HADOOP_PREFIX/etc/hadoop
ENV PATH="/usr/local/hadoop/bin:${PATH}"

RUN if [ "$(uname -m)" = "x86_64" ]; then export JAVA_HOME=/usr/lib/jvm/java-1.21.0-openjdk-amd64; else export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-arm64; fi \
    && export HADOOP_CLASSPATH=$JAVA_HOME/lib/tools.jar \
    && sed -i "/^export JAVA_HOME/ s:.*:export HADOOP_PREFIX=/usr/local/hadoop HADOOP_HOME=/usr/local/hadoop\n:" $HADOOP_PREFIX/etc/hadoop/hadoop-env.sh \
    && sed -i "/^export HADOOP_CONF_DIR/ s:.*:export HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop/:" $HADOOP_PREFIX/etc/hadoop/hadoop-env.sh \
    && echo "export JAVA_HOME=$JAVA_HOME" >> $HADOOP_PREFIX/etc/hadoop/hadoop-env.sh \
    && echo "export JAVA_HOME=$JAVA_HOME" >> /root/.bashrc

# Download and setup Apache Spark
RUN curl -s "https://archive.apache.org/dist/spark/spark-3.5.1/spark-3.5.1-bin-hadoop3.tgz" | tar -xz  -C /usr/local/ \
    && ln -s /usr/local/spark-3.5.1-bin-hadoop3 /usr/local/spark \
    && chmod a+rwx -R /usr/local/spark/
ENV PATH="/usr/local/spark/bin:${PATH}"
ENV SPARK_HOME /usr/local/spark

# Make vim nice
RUN echo "set background=dark" >> ~/.vimrc
ENV PYSPARK_PYTHON=python3

